import type { Scenario } from "./types"

export const SCENARIOS: Scenario[] = [
  {
    id: "s1_celebrity",
    title: "有名人なりすましDM詐欺",
    category: "投資勧誘型なりすまし",
    difficulty: "intermediate",
    platform: "instaglam",
    kind: "dm",
    profile: {
      displayName: "高橋啓一郎",
      handle: "takahashi_keiichiro_0fficial",
      avatar: "/avatars/influencer.png",
      verified: false,
      followerCount: 8500,
      followingCount: 12,
      postCount: 15,
      accountCreated: "2025年1月",
      accountAge: "作成から約7か月",
      bio: "投資家 / 実業家 📈 みんなを豊かに！公式アカウント",
      authenticHandle: "takahashi_keiichiro_official",
      authenticNote: "本物は「official」。この相手は o が数字の 0 に置き換えられています。",
    },
    message:
      "フォローありがとうございます！🙌\nいつも応援してくれる方へ、今回特別に投資のチャンスをシェアします。\n月利30%の仮想通貨自動売買システムで、すでに多くの方が成果を出しています。\n残り3名様限定なのでお早めに！\n詳しい説明はこちらのLINEで↓",
    link: {
      displayUrl: "line.me/ti/p/invest-vip",
      actualDomain: "line-invest-vip.xyz",
      suspicious: true,
      note: "公式のline.meではなく、末尾が .xyz の別ドメインへ転送されます。",
    },
    timestamp: "20:30",
    isFraud: true,
    correctAction: "block",
    checkpoints: [1, 2, 3, 4, 5, 6],
    redFlags: [
      "アカウント名が本物と1文字違い（official → 0fficial）",
      "認証バッジがない",
      "フォロワー8,500人（本物の有名人は数百万人規模）",
      "投稿がわずか15件",
      "月利30%をうたう投資勧誘DM",
      "「残り3名限定」で急がせる緊急性演出",
      "外部LINE（不審ドメイン）への誘導",
    ],
    explanation:
      "本物の有名人がDMで個別に投資を勧誘することはまずありません。名前の1文字違い・少ないフォロワー・投稿数・緊急性の演出が重なっており、典型的な投資勧誘型なりすましです。ブロック・通報が正解です。",
    tip: "「o」と「0」、「l(エル)」と「1」など、見間違えやすい文字の置き換えは要注意。IDをコピーして本物と1文字ずつ比べましょう。",
    realCase: {
      source: "警察庁（令和7年）",
      stat: "SNS型投資詐欺 認知件数 9,538件 / 被害額 約1,274億円（前年比46.3%増）",
    },
  },
  {
    id: "s2_hacked_friend",
    title: "知人アカウント乗っ取り",
    category: "アカウント乗っ取り連鎖型",
    difficulty: "intermediate",
    platform: "liner",
    kind: "dm",
    profile: {
      displayName: "佐藤みなみ",
      handle: "minami_sato",
      avatar: "/avatars/sato.png",
      verified: false,
      followerCount: 342,
      followingCount: 301,
      postCount: 128,
      accountCreated: "2019年4月",
      accountAge: "作成から約6年",
      bio: "カフェ巡り☕ / 写真 / 都内在住",
      authenticNote:
        "アカウント自体は本物の友人ですが、乗っ取られてなりすましメッセージが送られています。",
    },
    message:
      "ねえ、この投稿見た？😱\nあなたの写真が勝手に使われてるみたいなんだけど…\n本当にあなたか確認した方がいいと思う！\nすぐここから確認してみて→",
    link: {
      displayUrl: "instagram-verify-2024.com/check",
      actualDomain: "instagram-verify-2024.com",
      suspicious: true,
      note: "公式ドメインは instagram.com。年号や verify を含む別ドメインは偽サイトです。",
    },
    timestamp: "23:14",
    isFraud: true,
    correctAction: "suspicious",
    checkpoints: [4, 5, 6, 7],
    redFlags: [
      "普段の友人の文体・話し方と違う",
      "公式ではない不審なURL（instagram-verify-2024.com）",
      "「すぐ確認して」と急がせる",
      "アカウントが本物でも乗っ取られている可能性",
    ],
    explanation:
      "アカウントが本物でも、乗っ取られてなりすましDMが送られるケースです。リンクは絶対に踏まず、電話など別の手段で本人に直接確認するのが正解。焦って開かないことが被害連鎖を止めます。",
    tip: "「本物のアカウントから来た＝安全」ではありません。文面の違和感＋不審リンクの組み合わせは乗っ取りのサインです。",
    realCase: {
      source: "デジタルデータソリューション",
      stat: "乗っ取られた知人になりすましてリンクを送る手口が多発。連鎖的に被害が拡大。",
    },
  },
  {
    id: "s_genuine_friend",
    title: "本物の友人からの連絡",
    category: "本物（正しく信頼する）",
    difficulty: "beginner",
    platform: "liner",
    kind: "dm",
    profile: {
      displayName: "前田まい",
      handle: "mai_maeda",
      avatar: "/avatars/mai.png",
      verified: false,
      followerCount: 289,
      followingCount: 264,
      postCount: 76,
      accountCreated: "2018年6月",
      accountAge: "作成から約7年",
      bio: "パン作りとお昼寝が好き🍞 / 三姉妹の長女",
      authenticNote: "長年やり取りのある本物の友人アカウントです。",
    },
    message:
      "久しぶり！元気にしてた？😊\n来月の同窓会、駅前の「あおぞら食堂」で18時からだって。\n都合どうかな？行けそうなら幹事に伝えておくね〜",
    timestamp: "12:05",
    isFraud: false,
    correctAction: "trust",
    checkpoints: [4, 6, 7],
    redFlags: [],
    explanation:
      "金銭・投資の話も、不審なリンクも、緊急性の演出もありません。普段どおりの自然な内容で、プロフィールとも矛盾がない本物の連絡です。すべてを疑いすぎると本物まで遮断してしまうため、正しく「信頼する」判断も大切です。",
    tip: "詐欺対策は「全部ブロック」ではありません。危険サインが1つもないかを確認し、なければ落ち着いて信頼することも見抜く力のうちです。",
  },
  {
    id: "s3_authcode",
    title: "認証コード詐取",
    category: "アカウント乗っ取り（認証コード）",
    difficulty: "beginner",
    platform: "liner",
    kind: "dm",
    profile: {
      displayName: "山田太郎",
      handle: "yamada_taro_22",
      avatar: "/avatars/acquaintance.png",
      verified: false,
      followerCount: 58,
      followingCount: 190,
      postCount: 3,
      accountCreated: "2025年7月",
      accountAge: "作成から約1か月",
      bio: "よろしくお願いします",
      authenticNote: "身元が確実でない相手。知人を装っている可能性があります。",
    },
    message:
      "ごめん、間違えてあなたの電話番号で認証コードを送っちゃったんだけど届いてない？💦\nもし6桁の番号が届いてたら、それ教えてもらえる？\n急いでるから早めにお願い！🙏",
    timestamp: "19:47",
    isFraud: true,
    correctAction: "block",
    checkpoints: [3, 4, 6],
    redFlags: [
      "認証コード（6桁）を他人に教えるよう求めている",
      "認証コードには「他人に教えない」と明記されている",
      "相手の身元が確実でない（新規・投稿ほぼなし）",
      "「急いで」と焦らせている",
    ],
    explanation:
      "これはあなたのアカウントを乗っ取るために認証コードを聞き出す手口です。認証コードは、どんな相手にも絶対に教えてはいけません。教えずにブロックが正解です。",
    tip: "「あなた宛てに届いたコードを他人が欲しがる」時点で100%危険。相手が誰であってもコードは共有しないのが鉄則です。",
    realCase: {
      source: "大阪府警・新潟県",
      stat: "SNS乗っ取りで「認証コードを教えて」と聞き出す手口が全国で注意喚起されている。",
    },
  },
  {
    id: "s4_brand_campaign",
    title: "企業公式なりすましキャンペーン",
    category: "偽キャンペーン・フィッシング",
    difficulty: "intermediate",
    platform: "instaglam",
    kind: "dm",
    profile: {
      displayName: "GLAM公式ストア",
      handle: "glam_store.official",
      avatar: "/avatars/brand.png",
      verified: false,
      followerCount: 4200,
      followingCount: 88,
      postCount: 8,
      accountCreated: "2025年6月",
      accountAge: "作成から約2か月",
      bio: "GLAM公式｜最新キャンペーン情報をお届け🎁",
      authenticHandle: "glam_store_official",
      authenticNote: "本物はアンダースコア区切り。この相手はドット( . )に置き換えられています。",
    },
    message:
      "🎉ご当選おめでとうございます！🎉\nGLAM公式キャンペーンで最新モデルが当選しました！\n受け取りには本人確認が必要です。\n下記より配送先とお支払い情報（クレジットカード）をご登録ください。\n24時間以内のご登録が必要です。",
    image: "/content/campaign.png",
    mediaLabel: "キャンペーン",
    link: {
      displayUrl: "glam-campaign-win.info/claim",
      actualDomain: "glam-campaign-win.info",
      suspicious: true,
      note: "公式サイトのドメインと一致しません。.info の当選ページは典型的な偽サイトです。",
    },
    timestamp: "18:02",
    isFraud: true,
    correctAction: "block",
    checkpoints: [1, 2, 4, 5],
    redFlags: [
      "IDが公式と1文字違い（_ と . の置き換え）",
      "認証バッジがない",
      "応募していないのに「当選」通知",
      "クレジットカード情報の入力を要求（公式は要求しない）",
      "不審なドメイン（.info）の当選ページ",
      "「24時間以内」の緊急性演出",
    ],
    explanation:
      "応募していない当選通知と、カード情報の入力要求はフィッシングの典型です。公式キャンペーンが当選時にカード情報を求めることはありません。ブロック・通報が正解です。",
    tip: "「当選」で気持ちが高ぶった瞬間が狙われます。まず公式アカウント（正規ID・認証バッジ）でキャンペーンの有無を確認しましょう。",
    realCase: {
      source: "リリーフサイン（社会リスク対策）",
      stat: "大手ブランドを装う偽当選DMで偽サイトへ誘導し、カード情報を詐取する事例が報告されている。",
    },
  },
  {
    id: "s5_fake_ec",
    title: "偽ECサイト誘導（SNS広告）",
    category: "偽ショッピングサイト誘導",
    difficulty: "advanced",
    platform: "xtter",
    kind: "feed",
    isAd: true,
    mediaLabel: "広告",
    profile: {
      displayName: "ラグジュアリーアウトレット",
      handle: "luxury_outlet_jp",
      avatar: "/avatars/brand.png",
      verified: false,
      followerCount: 1120,
      followingCount: 0,
      postCount: 4,
      accountCreated: "2025年7月",
      accountAge: "作成から約3週間",
      bio: "在庫一掃セール実施中｜数量限定・早い者勝ち",
      authenticNote: "最近作成されたばかりの広告アカウントです。",
    },
    message:
      "【閉店セール】全品80%OFF！🛍️\n有名ブランドのバッグ・財布が驚きの価格に。\n在庫わずか、今すぐチェック👇\nbrand-outlet-sale.xyz",
    image: "/content/luxury-sale.png",
    link: {
      displayUrl: "brand-outlet-sale.xyz",
      actualDomain: "brand-outlet-sale.xyz",
      suspicious: true,
      note: "会社概要・特定商取引法の表記がなく、ドメインは .xyz。画像も他サイトからの転載が疑われます。",
    },
    timestamp: "9分前",
    isFraud: true,
    correctAction: "suspicious",
    checkpoints: [2, 3, 5, 6],
    redFlags: [
      "80%OFFなど非現実的な値引き率",
      "広告アカウントが最近作成されたばかり",
      "会社概要・特定商取引法の表記がない",
      "ドメインが .xyz で公式と一致しない",
      "「在庫わずか」で急がせる",
    ],
    explanation:
      "極端な値引きと新規アカウント、事業者表記のなさは偽ECサイトの典型です。すぐ購入せず、まずブランド名をGoogleで検索して公式サイトを確認し、広告を報告しましょう。",
    tip: "「安すぎる」は最大の危険信号。リンクから直接買わず、公式サイトを別途検索して価格や在庫を確かめる習慣を。",
    realCase: {
      source: "guardian.jpn.com",
      stat: "SNS広告経由で偽ECサイトへ誘導し、代金だけ詐取する被害が継続的に発生している。",
    },
  },
  {
    id: "s6_deepfake",
    title: "ディープフェイク偽投資広告",
    category: "AI生成コンテンツを使った広告",
    difficulty: "advanced",
    platform: "xtter",
    kind: "feed",
    isAd: true,
    mediaLabel: "動画広告",
    profile: {
      displayName: "資産グロース研究所",
      handle: "kabu_master_official",
      avatar: "/avatars/economist.png",
      verified: false,
      followerCount: 2360,
      followingCount: 3,
      postCount: 6,
      accountCreated: "2025年6月",
      accountAge: "作成から約2か月",
      bio: "元大手証券アナリスト｜確実に増やす投資術を無料公開",
      authenticNote: "実在の経済人を装う架空アカウント。動画はAI生成の疑いがあります。",
    },
    message:
      "【緊急公開】あの著名経済人が語る！📉➡📈\n「この投資アプリで月300万円は誰でも稼げる」\n確実に儲かる自動売買システムを、今だけ無料でLINEグループに公開中。\n定員に達し次第締め切ります。",
    image: "/content/deepfake-video.png",
    // public/content/deepfake.mp4 を置けば本物の動画として再生される。
    // 置かない場合は上の image がゆっくり動く疑似再生になる（体験の流れは同じ）。
    video: undefined,
    videoDurationSec: 17,
    videoGlitch: true,
    // 端末の読み上げ機能でしゃべらせる。動画ファイルが無くても「声」で現実味が出る
    videoSpeech: [
      { at: 0.6, text: "皆さん、こんにちは。" },
      { at: 3.4, text: "この投資アプリなら、月三百万円は誰でも稼げます。" },
      { at: 8.6, text: "確実に儲かる自動売買システムです。" },
      { at: 12.4, text: "定員に達し次第締め切ります。今すぐ登録してください。" },
    ],
    link: {
      displayUrl: "▶ LINEグループに参加する",
      actualDomain: "line-vip-invest.xyz",
      suspicious: true,
      note: "著名人本人の公式ではなく、外部の投資グループ（不審ドメイン）へ誘導しています。",
    },
    timestamp: "3分前",
    isFraud: true,
    correctAction: "block",
    checkpoints: [4, 5, 6, 7],
    redFlags: [
      "有名経済人が投資を勧める内容（通常あり得ない）",
      "「月300万」「確実に儲かる」の誇大表現",
      "LINEグループなど外部への誘導",
      "動画の口元・音声が不自然（ディープフェイクの兆候）",
      "「定員締め切り」の緊急性演出",
    ],
    explanation:
      "著名人が広告で投資を断言する動画は、AIで作られたディープフェイクの可能性が極めて高いです。口元の動きや音声の違和感、外部グループ誘導が兆候。ブロック・通報が正解です。",
    tip: "「本人が言っている映像」でも本物とは限りません。発言内容を本人の公式アカウントや報道で必ず裏取りを。",
    realCase: {
      source: "警察庁（令和7年）",
      stat: "SNS型投資詐欺の当初接触ツールはInstagramが最多（1,934件）、次いでYouTube（1,229件）。",
    },
  },
]
